class TestSQLite3DirectoryRepository:
    class TestCreateDirectory:
        ...

    class TestCreateDirectories:
        ...

    class TestUpdateDirectory:
        ...

    class TestGetDirectories:
        ...

    class TestIsDuplicate:
        ...

    class TestGetNormalizedPath:
        ...

    class TestBuildDirectoryGraph:
        ...

    class TestRegisterNode:
        ...

    class TestRegisterNodeBatch:
        ...

    class TestRegisterNodeEdges:
        ...

    class TestRegisterNodeReflectionBatch:
        ...

    class TestPruneDirectoriesWithoutRoot:
        ...
