class TestFolderHandlers:
    class TestAddFolderCommandHandler:
        ...

    class TestRemoveFolderCommandHandler:
        ...

    class TestRenameFolderSetCommandHandler:
        ...

    class TestAddFolderSetCommandHandler:
        ...

    class TestDeleteFolderSetCommandHandler:
        ...

    class TestSetFolderEnabledCommandHandler:
        ...

    class TestSetAllFoldersEnabledCommandHandler:
        ...

    class TestMoveFolderBetweenFolderSetsCommandHandler:
        ...
